sudo: required

language: python

services:
  - docker

env:
  global:
    - DOCKER_REPO="laslabs/alpine-odoo"
    - PROD_BRANCH="master"
  matrix:
    - ODOO_VERSION="10.0"
    - ODOO_VERSION="9.0"

before_install:
  - docker pull kiasaki/alpine-postgres
  - docker run -d -e POSTGRES_USER="odoo" -e POSTGRES_PASSWORD="odoo" --name="db" kiasaki/alpine-postgres

install:
  - docker build --tag="${DOCKER_REPO}:${ODOO_VERSION}" --build-arg ODOO_VERSION=$ODOO_VERSION $TRAVIS_BUILD_DIR/

script:
  - docker run -d -t --publish="8069:8069" --name="$TRAVIS_BUILD_NUMBER" --link="db:db" "${DOCKER_REPO}:${ODOO_VERSION}"
  - sleep 5  # Let Odoo boot
  - curl --fail http://localhost:8069/web

after_success:
  - 'if [ "$TRAVIS_BRANCH" == "$PROD_BRANCH" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; \
      then \
        docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && docker push $DOCKER_REPO:$ODOO_VERSION; \
      fi'
